"""initial database setup

Revision ID: 6b2c30937fe4
Revises: 
Create Date: 2025-12-03 02:52:29.546482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2c30937fe4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('last_donation_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('hospital_name', sa.String(length=100), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('utr_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('profile_image', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transaction')
    op.drop_table('donor')
    op.drop_table('blood_stock')
    # ### end Alembic commands ###
